### ISSUE TITLE
prefixLink unnecessary in profilePic

### ISSUE THREAD

**Issue by charandas** [wpioneer/gatsby-starter-lumen#32]
I am new to Gatsby, so taking a hunch at this.

I could not get the profilePic to work without first removing prefixLink [here](https://github.com/wpioneer/gatsby-starter-lumen/blob/master/components/SiteSidebar/index.jsx#L18).

So,

```js
<img src={prefixLink(profilePic)} width='75' height='75' />
// becomes
<img src={profilePic} width='75' height='75' />
```

See [Gatsby's config](https://github.com/gatsbyjs/gatsby/blob/030be989c4bf5baa04eb6fc98dee85f43280bda9/lib/utils/webpack.config.js#L51). It seems to be accounting for the prefixLink there.

**Comment by abisz** [comment]
Hey @charandas,
I also think the prefixLink() can be removed, because the image is not linked but just "inline-dumped". 
What kind of image did you use to break it? Did the default image also not work?

**Comment by charandas** [comment]
@abisz My image was a jpeg 102K in size. Gatsby's webpack config caps inline-dumping at 10K.

The default image is 4.3K, so it works just fine.

**Comment by abisz** [comment]
@charandas or we just change it not to inline it with the data url (which is a bad practice anyway) and just display it as a normal asset.
@wpioneer Is there a particular reason the image is included in that way?

**Comment by wpioneer** [comment]
@abisz @charandas In the gatsby, inline-dumping is used by default for **small** images. (https://github.com/gatsbyjs/gatsby/blob/master/lib/utils/webpack.config.js#L260)

You can override this in gatsby-node.js, if you want. On an example of how to overriden SVG - https://github.com/wpioneer/gatsby-starter-lumen/blob/master/gatsby-node.js#L16 Also here you can change the limit.

(SVG is overridden, since it was a forced necessity to display the icons).

====

If the image is larger than 10K, then it should not be loaded inline.
I checked it and do not understand why it works differently for you.

**Comment by abisz** [comment]
That's cool, I didn't know there was this mechanism to load it based on the size.
I tested it as well, works fine for me.

@charandas did you have this problem when developing or only when building the site?

**Comment by charandas** [comment]
@abisz I had this problem when deploying. My prefixlink is "/blog", I see
the image url become baseURL/blog/blog/hash.jpeg which is incorrect.

As I said above, Gatsby now includes prefixLink in its base webpack config;
so we need not do that for assets, like currently in SiteSideBar template.

**Comment by wpioneer** [comment]
@charandas Thank you for noticing, now it is clear. Can you send PR for the SiteSidebar component?

**Comment by charandas** [comment]
Sure @wpioneer. Done.
